import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import { print } from "graphql";
import { typeDefs } from "@/typeDefs";

// Exports the GraphQL schema (SDL) so frontend developers can run client codegen and IDE tooling.
// Run with: yarn export-schema

const OUTPUT_DIR = join(process.cwd(), "docs", "frontend-integration");
const OUTPUT_FILE = join(OUTPUT_DIR, "schema.graphql");

const banner = `# Car Rental Management — GraphQL schema (SDL)
# Generated by \`yarn export-schema\` from src/typeDefs.ts. Do not edit by hand.
`;

mkdirSync(OUTPUT_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, `${banner}\n${print(typeDefs)}`);

console.log(`Wrote schema to ${OUTPUT_FILE}`);
